Docker testing
JetBrains-Research/plugin-utilities pull request #19
Opened 2021-08-13 12:16 UTC by Furetur

2021-08-13 18:15 UTC, SpirinEgor commented on README.md
> +1. Build docker image `sudo docker build --tag plugin-utilities .`
Еще можно просто спалить, это как правило быстрее и не так требовательно к ресурсам.
```
docker pull tag
```

2021-08-13 18:15 UTC, SpirinEgor commented on README.md
> +2. Run the tests `sudo docker run -v $(pwd):/repo plugin-utilities`
Давай лучше в доке указывать тег, как и на хабе. С именем пользователя

2021-08-13 18:18 UTC, Furetur commented on README.md
> +2. Run the tests `sudo docker run -v $(pwd):/repo plugin-utilities`
То есть ты советуешь заменить всю дока скачивание образа и на использование готового скачанного образа?

2021-08-13 18:58 UTC, SpirinEgor commented on README.md
> +2. Run the tests `sudo docker run -v $(pwd):/repo plugin-utilities`
Оо, зачем менять всю доку? Я просто прошу теги правильно расставить. И добавить опцию про pull. Тип пользователь может либо сбилдить, либо спуллить

2021-08-13 18:58 UTC, SpirinEgor commented on README.md
> +2. Run the tests `sudo docker run -v $(pwd):/repo plugin-utilities`
Ну то есть надо вместо 2 строчек 3 написать

2021-08-14 08:59 UTC, SpirinEgor approved these changes

2021-08-16 07:40 UTC, nbirillo requested changes
Almost had done, thank you!

2021-08-16 07:40 UTC, nbirillo commented on Dockerfile
> +RUN git clone https://github.com/JetBrains-Research/plugin-utilies-mock-data /mock-data
Are you sure about this url?  Should we replace with https://github.com/JetBrains-Research/plugin-utilies-mock-data.git?

2021-08-16 07:56 UTC, merged