Testing on real Gradle projects from Github
JetBrains-Research/plugin-utilities pull request #25
Opened 2021-08-26 10:59 UTC by Furetur

2021-09-13 10:30 UTC, nbirillo commented
@Furetur could you please finish this PR?

2021-09-14 08:21 UTC, Furetur commented
@nbirillo Yes, of course! Lately I've been a little bit busy building and fixing prehistorical Java projects :)

2021-11-21 15:51 UTC, nbirillo requested changes

2021-11-21 15:51 UTC, nbirillo commented on .github/workflows/test-on-projects.yml
> +      - github-testing
Could you please delete this branch from yml file?
Probably we should run this action on push and pr into main branches

2022-12-05 22:24 UTC, closed without merging