Open repo
JetBrains-Research/plugin-utilities pull request #9
Opened 2021-07-16 13:39 UTC by Furetur

2021-08-12 08:10 UTC, Furetur commented on plugin-utilities-core/src/main/kotlin/org/jetbrains/research/pluginUtilities/openRepository/RepositoryOpener.kt
> +    private fun closeSingleProject(project: Project) =
Вроде бы, да. Настя так же закрывала проекты. Я, пока что, не замечал ошибок от этой функции, когда открывал полноценные проекты с билд файлами

2021-08-13 09:31 UTC, nbirillo commented on plugin-utilities-core/src/main/kotlin/org/jetbrains/research/pluginUtilities/openRepository/RepositoryOpener.kt
> +    private fun closeSingleProject(project: Project) =
У нас она не кидает ошибок, значит у вас что-то не так с потоками, если у вас AlreadyDisposedException

2021-08-14 08:01 UTC, Furetur commented
Now everything runs in Docker and therefore is super sexy

2021-08-14 08:56 UTC, SpirinEgor approved these changes
LGTM

2021-08-16 07:45 UTC, nbirillo requested changes
Great!

2021-08-16 07:45 UTC, nbirillo commented on .github/workflows/test-on-projects.yml
> +  workflow_dispatch: {}
Please, delete open_repo from this. It is a temporary branch
Instead of it you can run these tests on PR in the main branch

2021-08-16 10:12 UTC, nbirillo approved these changes
Great!

2021-08-16 12:09 UTC, merged